import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const DBHeaventRounded = localFont({
  src: "../fonts/DB-Heavent-Rounded.ttf",
  variable: "--font-db-heavent-rounded",
});

const DBHeaventRoundedBold = localFont({
  src: "../fonts/DB-HeaventRounded-Bd.ttf",
  variable: "--font-db-heavent-rounded-bold",
});

const DBHeaventRoundedMed = localFont({
  src: "../fonts/DB-HeaventRounded-Med.ttf",
  variable: "--font-db-heavent-rounded-med",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
                  ${DBHeaventRounded.variable} ${DBHeaventRoundedBold.variable} 
                  ${DBHeaventRoundedMed.variable} antialiased max-w-screen`}
      >
        {children}
      </body>
    </html>
  );
}
